name: Unit Tests backend and Linting

on:
  push:
  workflow_dispatch:

jobs:
  run-tests-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Run tests
        run: pytest -v --cov=src/server/ -s src/tests/

#      - name: Run mypy
#        run: mypy $(git ls-files '*.py')

      #- name: Run pylint
      #  run: pylint $(git ls-files '*.py')

      - name: Run Black
        run: black **/*.py

  notify-on-failure:
    needs: run-tests-and-lint
    if: failure() || cancelled()
    uses: IronWatchers/tgWatcher/.github/workflows/reusable-error-notification.yml@main
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    with:
      color: 'yellow'
